"""initial_schema

Revision ID: 26709576b12c
Revises: 
Create Date: 2026-03-09 16:45:18.819060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '26709576b12c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_api_keys', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.alter_column('auth_api_keys', 'channel_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.alter_column('channels', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.alter_column('videos', 'channel_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'channel_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.alter_column('channels', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.alter_column('auth_api_keys', 'channel_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.alter_column('auth_api_keys', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###
