"""empty message

Revision ID: 4b96c82d4c0a
Revises: e607de2a635e
Create Date: 2026-03-10 09:18:40.912228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4b96c82d4c0a'
down_revision: Union[str, Sequence[str], None] = 'e607de2a635e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_api_keys', 'channel_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_api_keys', 'channel_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###
